config/routes.rb
Postmaster::Application.routes.draw do
  devise_for :user do
      
  end
  
  resources :posts do
        resources :replies
        get 'run', :on=>:member
        get 'check', :on=>:member
  end
  
  get "home/index"

  match 'process_posts' => 'posts#dowork', :as => :process_posts

   root :to => "home#index"

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :replies, :dependent => :delete_all 
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :posts,:dependent => :delete_all 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    redirect_to new_user_session_path unless current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_filter :authenticate
  
  def index
  end
  

    def authenticate
      redirect_to new_user_session_path unless current_user
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper
  def new
  end
  
  def create
    @post = current_user.posts.build(params[:post])
    if @post.save
      respond_to do |format|
        format.html { redirect_to( :back, :notice => 'Post was successfully created.') }
      end
    else
      respond_to do |format|
        format.html { render :back, :error => "Creating post failed." }  
      end    
    end
  end
  
  def destroy
     post=  current_user.posts.find_by_id(params[:id])
      current_user.posts.delete(post)
      redirect_to :back
  end
  
  def dowork
    posts = Post.find(:all)
    posts.each { |post|
        replypost(post) unless checkpage(post)

    }
    
    redirect_to :back, :notice=>"did work"
  end

  def run
    post=  current_user.posts.find_by_id(params[:id])
    replypost(post)
    #redirect_to :back, :notice=>"replied"
  end
  
  def check
    post=  current_user.posts.find_by_id(params[:id])
    firstpage = checkpage(post)
    redirect_to :back, :notice=>"First page: #{firstpage}"
  end
  
end

app/controllers/publish_controller.rb
class PublishController < ApplicationController
  def process  
    users = User.find(:all)
    users.each do |user|
      user.posts.each do |post|
        post.run
      end
    end
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def new
    @post = current_user.posts.find_by_id(params[:post_id])
    @reply = @post.replies.build
    render :partial => 'shared/replyform'
  end
  
  def create
    @post = current_user.posts.find_by_id(params[:post_id])
    @reply = @post.replies.build(params[:reply])
    
    if @reply.save
      respond_to do |format|
        format.html { redirect_to :controller=>:home, :action=>:index, :notice => 'Reply was successfully created.' }
      end
    else
      respond_to do |format|
        format.html { render :partial => 'shared/replyform' , :error => "Creating reply failed." }  
      end    
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
require "uri" 
require "net/http" 
require 'open-uri'
require 'nokogiri'
require 'hpricot'

module PostsHelper
    def replypost(post)
          post.replies.each do |reply|
            params = { 
              'action'=>'addreply',
              'forum'=>post.forum,
              'topic'=>post.topic,
              'membername'=>reply.membername,
              'password'=>reply.password,
              'inpost'=>reply.inpost+ " #{Time.now}",
              'Submit'=>'submit',
            }
            
            link = "http://163.ca/cgi-bin/lb5000/post.cgi?action=reply&forum=#{post.forum}&topic=#{post.topic}"
            
            @x = Net::HTTP.post_form(URI.parse(link), params) 
 
          end
          p "replied #{post.to_s}}"
  end
  
  def checkpage(post)
      @content =''
      pages= [0]
      #pages= [0] if (post.user.email=='postmaster@gmail.com')
      postlink="topic=#{post.topic}"
      pages.each { |page|
        
        weblink="http://163.ca/cgi-bin/lb5000/forums.cgi?forum=#{post.forum}&show=#{page}"
	      @content += Net::HTTP.get(URI.parse(weblink))
        return true if @content.include?(postlink)
      }

      false
  end

end

app/helpers/publish_helper.rb
module PublishHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/home/index.html.erb
			    <%= link_to "Sign up", new_user_registration_path %> or  
			    <%= link_to "Sign in", new_user_session_path %>   
			     <%= link_to "Sign out", destroy_user_session_path %>   
<h2>Welcome to postermaster</h2>
You are logged in as <%=current_user.email%>


  <div>
    <%= render :partial=>'shared/post', :collection =>current_user.posts%>
    <%= render :partial=>'shared/postform'%>
    <%=button_to 'process posts', :process_posts, {:method=>:get}%>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postmaster</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
<%= yield %>

</body>
</html>

app/views/posts/check.html.erb
<%=raw @link%>

app/views/posts/run.html.erb
  <div>
   <%if @x%>  <%=raw(@x.body)%> <%end%>
  </div>

app/views/shared/_post.html.erb
<div>
  <table>
    <tr>
      <td>
      <h3><%= post.subject%></h3>
      forum:<%= post.forum%></br>
      topic:<%= post.topic%></br>
      <div>
       
        <%= render :partial =>'shared/reply', :collection=> post.replies%>
      <div>
      </td>
      <td>
      <%=button_to 'add reply', new_post_reply_path(post), {:method =>"get"}%>

          <%=button_to 'remove', post_path(post), {:method =>"delete"}%>
          <%=button_to 'Reply', run_post_path(post), {:method=>:get}%>
          <%=button_to 'check', check_post_path(post), {:method=>:get}%>
      </td>
    </tr>
   </table>
  
 </div>

app/views/shared/_postform.html.erb
<%= form_for( @post||current_user.posts.build) do |f|%>
<div>
  <%= f.label :subject%>
  <%= f.text_field :subject%><br/>
    <%= f.label :forum%>
  <%= f.text_field :forum%><br/>
    <%= f.label :topic%>
  <%= f.text_field :topic%>
  </div>
  <%= f.submit %>
<%end%>

app/views/shared/_reply.html.erb
  <table>
    <tr>
        <td><b>username</b></td> 
        <td> <%= reply.membername%></td> 

    </tr>
    <tr>   
        <td><b>password</b></td> 
        <td> <%=  reply.password%></td> 
        
    </tr>   
    <tr>   
        <td><b>content</h3></b>  
       <td>  <%=  reply.inpost%></td> 
    
    </tr>
  </table>

app/views/shared/_replyform.html.erb
<%= form_for([@post,@reply]) do |f|%>
  <table>
    <tr>
        <td> <%= f.label :membername%></td> 
        <td> <%= f.text_field :membername%></td> 
    </tr>
    <tr>   
        <td> <%= f.label :password%></td> 
        <td> <%= f.text_field :password%></td> 
    </tr>   
    <tr>    
       <td>  <%= f.label :inpost%></td> 
        <td> <%= f.text_field :inpost%>  </td> 
    </tr>
  </table>
  <%= f.submit %>
<%end%>